version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: shipping-management-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: shipping_management_db
      MYSQL_USER: shipping_user
      MYSQL_PASSWORD: shipping123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
